// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	user "BE-hi-SPEC/features/user"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddFavorite provides a mock function with given fields: token, productID
func (_m *Service) AddFavorite(token *jwt.Token, productID uint) (user.Favorite, error) {
	ret := _m.Called(token, productID)

	var r0 user.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) (user.Favorite, error)); ok {
		return rf(token, productID)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) user.Favorite); ok {
		r0 = rf(token, productID)
	} else {
		r0 = ret.Get(0).(user.Favorite)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, uint) error); ok {
		r1 = rf(token, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DelFavorite provides a mock function with given fields: token, favoriteID
func (_m *Service) DelFavorite(token *jwt.Token, favoriteID uint) error {
	ret := _m.Called(token, favoriteID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) error); ok {
		r0 = rf(token, favoriteID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUser provides a mock function with given fields:
func (_m *Service) GetAllUser() ([]user.User, error) {
	ret := _m.Called()

	var r0 []user.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]user.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []user.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: userID
func (_m *Service) GetUser(userID uint) (user.Favorite, error) {
	ret := _m.Called(userID)

	var r0 user.Favorite
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (user.Favorite, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) user.Favorite); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(user.Favorite)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HapusUser provides a mock function with given fields: token, userID
func (_m *Service) HapusUser(token *jwt.Token, userID uint) error {
	ret := _m.Called(token, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, uint) error); ok {
		r0 = rf(token, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email, password
func (_m *Service) Login(email string, password string) (user.User, error) {
	ret := _m.Called(email, password)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (user.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) user.User); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: newUser
func (_m *Service) Register(newUser user.User) (user.User, error) {
	ret := _m.Called(newUser)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user.User) (user.User, error)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(user.User) user.User); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(user.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUser provides a mock function with given fields: name
func (_m *Service) SearchUser(name string) ([]user.User, error) {
	ret := _m.Called(name)

	var r0 []user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]user.User, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []user.User); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: token, input
func (_m *Service) UpdateUser(token *jwt.Token, input user.User) (user.User, error) {
	ret := _m.Called(token, input)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, user.User) (user.User, error)); ok {
		return rf(token, input)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, user.User) user.User); ok {
		r0 = rf(token, input)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, user.User) error); ok {
		r1 = rf(token, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
