# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CONTAINER_NAME }}
            docker rm ${{ secrets.CONTAINER_NAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}
            docker run --name ${{ secrets.CONTAINER_NAME }} -d -p 8000:8000 --link mysqlku -e DBHOST=${{ secrets.DB_HOST }} -e DBUSER=root -e DBPASS=${{ secrets.DBPASS }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e CLOUDINARY_CLD=${{ secrets.CLOUDINARY_CLD }} -e CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }} -e CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }} -e CLOUDINARY_FOLDER=${{ secrets.CLOUDINARY_FOLDER }} -e OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }} -e MIDTRANS_KEY=${{ secrets.MIDTRANS_KEY }} -e GOMAIL_NAME=${{ secrets.GOMAIL_NAME }} -e GOMAIL_EMAIL=${{ secrets.GOMAIL_EMAIL }} -e GOMAIL_PASS=${{ secrets.GOMAIL_PASS }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}